name: running test, build image, and deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  runningtest:
    name: running test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'
      - name: run test
        run: go test -v ./... -cover