name: running test, build image, and deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - development

jobs:
  runningtest:
    name: running test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'
      - name: run test
        run: go test -v ./... -cover

  buildimage:
    name: build image
    runs-on: ubuntu-latest
    needs: runningtest
    steps:
      - uses: actions/checkout@v2
      - name: create env
        run: |
          echo " ${{ secrets.ENV_PROJECT }} " > .env
      - name: build image
        run: docker build -t dikocesrt/habit-master:latest .
      - name: login registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push dikocesrt/habit-master